import { COLORS } from './colors';

export const FONTS = {
  Pretendard: 'Pretendard-Regular',
  PretendardMedium: 'Pretendard-Medium',
  PretendardSemiBold: 'Pretendard-SemiBold',
  PretendardBold: 'Pretendard-Bold',
  RobotoCondensed: 'RobotoCondensed-Regular',
  RobotoCondensedBold: 'RobotoCondensed-Bold',
  RobotoCondensedMedium: 'RobotoCondensed-Medium',
  RobotoCondensedSemiBold: 'RobotoCondensed-SemiBold',
};

export default {
  fontSize32_Semibold: {
    color: COLORS.textDefault,
    fontSize: 32,
    lineHeight: 38,
    fontFamily: FONTS.PretendardSemiBold,
  },
  fontSize32_Bold: {
    color: COLORS.textDefault,
    fontSize: 32,
    lineHeight: 38,
    fontFamily: FONTS.PretendardBold,
  },
  fontSize30_Bold: {
    color: COLORS.textDefault,
    fontSize: 30,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 36,
  },
  fontSize30_Semibold: {
    color: COLORS.textDefault,
    fontSize: 30,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 36,
  },
  fontSize28_Bold: {
    color: COLORS.textDefault,
    fontSize: 28,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 29,
  },
  fontSize24_Bold: {
    color: COLORS.textDefault,
    fontSize: 24,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 32,
  },
  fontSize24_Semibold: {
    color: COLORS.textDefault,
    fontSize: 24,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 32,
  },
  fontSize24_Medium: {
    color: COLORS.textDefault,
    fontSize: 24,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 32,
  },
  fontSize24_Regular: {
    color: COLORS.textDefault,
    fontSize: 24,
    fontFamily: FONTS.Pretendard,
    lineHeight: 32,
  },
  fontSize22_Bold: {
    color: COLORS.textDefault,
    fontSize: 22,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 32,
  },
  fontSize22_Semibold: {
    color: COLORS.textDefault,
    fontSize: 22,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 32,
  },
  fontSize22_Medium: {
    color: COLORS.textDefault,
    fontSize: 22,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 32,
  },
  fontSize22_Regular: {
    color: COLORS.textDefault,
    fontSize: 22,
    fontFamily: FONTS.Pretendard,
    lineHeight: 32,
  },
  fontSize20_Bold: {
    color: COLORS.textDefault,
    fontSize: 20,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 28,
  },
  fontSize20_Semibold: {
    color: COLORS.textDefault,
    fontSize: 20,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 28,
  },
  fontSize20_Medium: {
    color: COLORS.textDefault,
    fontSize: 20,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 28,
  },
  fontSize20_Regular: {
    color: COLORS.textDefault,
    fontSize: 20,
    fontFamily: FONTS.Pretendard,
    lineHeight: 28,
  },
  fontSize18_Bold: {
    color: COLORS.textDefault,
    fontSize: 18,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 24,
  },
  fontSize18_Semibold: {
    color: COLORS.textDefault,
    fontSize: 18,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 26,
  },
  fontSize18_Medium: {
    color: COLORS.textDefault,
    fontSize: 18,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 26,
  },
  fontSize18_Regular: {
    color: COLORS.textDefault,
    fontSize: 18,
    fontFamily: FONTS.Pretendard,
    lineHeight: 24,
  },
  fontSize16_Bold: {
    color: COLORS.textDefault,
    fontSize: 16,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 24,
  },
  fontSize16_Semibold: {
    color: COLORS.textDefault,
    fontSize: 16,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 20,
  },
  fontSize16_Medium: {
    color: COLORS.textDefault,
    fontSize: 16,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 24,
  },
  fontSize16_Regular: {
    color: COLORS.textDefault,
    fontSize: 16,
    fontFamily: FONTS.Pretendard,
    lineHeight: 24,
  },
  fontSize15_Bold: {
    color: COLORS.textDefault,
    fontSize: 15,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 20,
  },
  fontSize15_Semibold: {
    color: COLORS.textDefault,
    fontSize: 15,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 20,
  },
  fontSize15_Medium: {
    color: COLORS.textDefault,
    fontSize: 15,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 20,
  },
  fontSize15_Regular: {
    color: COLORS.textDefault,
    fontSize: 15,
    fontFamily: FONTS.Pretendard,
    lineHeight: 20,
  },
  fontSize14_Bold: {
    color: COLORS.textDefault,
    fontSize: 14,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 20,
  },
  fontSize14_Semibold: {
    color: COLORS.textDefault,
    fontSize: 14,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 20,
  },
  fontSize14_Medium: {
    color: COLORS.textDefault,
    fontSize: 14,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 20,
  },
  fontSize14_Regular: {
    color: COLORS.textDefault,
    fontSize: 14,
    fontFamily: FONTS.Pretendard,
    lineHeight: 20,
  },
  fontSize13_Bold: {
    color: COLORS.textDefault,
    fontSize: 13,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 20,
  },
  fontSize13_Semibold: {
    color: COLORS.textDefault,
    fontSize: 13,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 20,
  },
  fontSize13_Medium: {
    color: COLORS.textDefault,
    fontSize: 13,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 20,
  },
  fontSize13_Regular: {
    color: COLORS.textDefault,
    fontSize: 13,
    fontFamily: FONTS.Pretendard,
    lineHeight: 20,
  },
  fontSize12_Bold: {
    color: COLORS.textDefault,
    fontSize: 12,
    fontFamily: FONTS.PretendardBold,
    lineHeight: 16,
  },
  fontSize12_Semibold: {
    color: COLORS.textDefault,
    fontSize: 12,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 16,
  },
  fontSize12_Medium: {
    color: COLORS.textDefault,
    fontSize: 12,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 16,
  },
  fontSize12_Regular: {
    color: COLORS.textDefault,
    fontSize: 12,
    fontFamily: FONTS.Pretendard,
    lineHeight: 16,
  },
  fontSize11_Semibold: {
    color: COLORS.textDefault,
    fontSize: 11,
    fontFamily: FONTS.PretendardSemiBold,
    lineHeight: 14,
  },
  fontSize11_Medium: {
    color: COLORS.textDefault,
    fontSize: 11,
    fontFamily: FONTS.PretendardMedium,
    lineHeight: 14,
  },
  fontSize11_Regular: {
    color: COLORS.textDefault,
    fontSize: 11,
    fontFamily: FONTS.Pretendard,
    lineHeight: 14,
  },
  fontSize10_Regular: {
    color: COLORS.textDefault,
    fontSize: 10,
    fontFamily: FONTS.Pretendard,
    lineHeight: 16,
  },
  fontSize20_RobotoCondensed: {
    fontSize: 20,
    color: '#272C61',
    lineHeight: 28,
    fontFamily: FONTS.RobotoCondensedBold,
  },
  fontSize28_RobotoCondensed: {
    fontSize: 28,
    color: '#272C61',
    lineHeight: 38,
    fontFamily: FONTS.RobotoCondensedBold,
  },
};
