// authPage : 로그인 후 갈 수 있는 페이지
const authPage = {
  socialToken: 'socialToken',
  socialTokenDetail: 'socialTokenDetail',
  createWallet: 'createWallet',
  walletPwd: 'walletPwd',
  checkWalletPwd: 'checkWalletPwd',
  walletBackupCheck: 'walletBackupCheck',
  walletBackup: 'walletBackup',
  walletDetail: 'walletDetail',
  restoreWallet: 'restoreWallet',
  walletReceive: 'walletReceive',
  walletSetting: 'walletSetting',
  walletSend: 'walletSend',
  walletSendClear: 'walletSendClear',
  walletSending: 'walletSending',
  restoreSeedConfirm: 'restoreSeedConfirm',
  privateKeyConfirm: 'privateKeyConfirm',
  academyRegist: 'academyRegist',
  academyManagement: 'academyManagement',
  academyDetailSetting: 'academyDetailSetting',
  report: 'report',
  academyEdit: 'academyEdit',
  communityWrite: 'communityWrite',
  communityEdit: 'communityEdit',

  moreQuestion: 'moreQuestion',
  moreInquiry: 'moreInquiry',
  moreInquiryRegist: 'moreInquiryRegist',
  moreInquiryDetail: 'moreInquiryDetail',
  academyRecruitmentRegist: 'academyRecruitmentRegist',
  academyRecruitmentEdit: 'academyRecruitmentEdit',
  moreModifyChallenge: 'moreModifyChallenge',
  academyGroup: 'academyGroup',
  academyAdmin: 'academyAdmin',
  academyCompany: 'academyCompany',
  academyCompanyManagement: 'academyCompanyManagement',
  academyReport: 'academyReportDetails',
  academyReportDetailsView: 'academyReportDetailsView',
  academyPlayerDetail: 'academyPlayerDetail',
  academyPlayerProfileEdit: 'academyPlayerProfileEdit',
  academyGroupMove: 'academyGroupMove',
  academyMatchingRegistration: 'academyMatchingRegistration',
  matchingCancel: 'matchingCancel',
  matchingRegistReview: 'matchingRegistReview',
  matchingReject: 'matchingReject',
  matchingScore: 'matchingScore',
  matchingSelectAcademy: 'matchingSelectAcademy',
  matchingSelectScorer: 'matchingSelectScorer',
  matchingRegist: 'matchingRegist',
  academyScheduleWrite: 'academyScheduleWrite',
  academyScheduleEdit: 'academyScheduleEdit',
  moreMyInfo: 'moreMyInfo',
  moreProfile: 'moreProfile',
  moreMyDetail: 'moreMyDetail',
  moreMyDetailModify: 'moreMyDetailModify',
  moreMyDetailEdit: 'moreMyDetailEdit',
  moreCheckPhoneNo: 'moreCheckPhoneNo',
  moreSetting: 'moreSetting',
  moreNotification: 'moreNotification',
  moreStat: 'moreStat',
  moreStatModify: 'moreStatModify',
  moreCouponRegister: 'moreCouponRegister',
  moreCouponComplete: 'moreCouponComplete',
  moreArticleBookmarks: 'moreArticleBookmarks',
  moreGameSchedule: 'moreGameSchedule',
  moreMatchDetail: 'moreMatchDetail',
  moreActiveHistory: 'moreActiveHistory',
  moreTermsService: 'moreTermsService',
  academyRecruitmentForAdmin: 'academyRecruitmentForAdmin',
  matchingChatRoomListScreen: 'matchingChatRoomListScreen',
  matchingChatRoomScreen: 'matchingChatRoomScreen',
  moreAccountManage: 'moreAccountManage',
  moreChangePassword: 'moreChangePassword',
  swap: 'swap',
  swapTranfer: 'swapTranfer',
  tournamentApplyComplete: 'tournamentApplyComplete',
  traningVideoDetail: 'traningVideoDetail',
  traningRegistering: 'traningRegistering',
  traningClear: 'traningClear',
  trainingDetail: 'trainingDetail',
  videoPlayer: 'videoPlayer',
  addDetails: 'addDetails',
  masterVideoDetail: 'masterVideoDetail',
  masterVideoDetailPlayer: 'masterVideoDetailPlayer',
  challengeDetail: 'challengeDetail',
  challengeAddDetails: 'challengeAddDetails',
  challengeEditDetails: 'challengeEditDetails',
  challengeRegistering: 'challengeRegistering',
  challengeRegistrationComplete: 'challengeRegistrationComplete',
  challengeContentPlayer: 'challengeContentPlayer',
  challengeVideoPlayer: 'challengeVideoPlayer',
  moreNotice: 'moreNotice',
  moreNoticeDetail: 'moreNoticeDetail',
  unsubscribe: 'Unsubscribe',
  communityFavPlayerDetails: 'communityFavPlayerDetails',
};

// noAuthPage : 로그인과 상관없이 갈 수 있는 페이지
const noAuthPage = {
  login: 'login',
  termsService: 'termsService',
  identifyVerification: 'identifyVerification',
  alreadySign: 'alreadySign',
  inputEmail: 'inputEmail',
  inputPassword: 'inputPassword',
  userInfo: 'userInfo',
  performanceInfo: 'performanceInfo',
  completeSign: 'completeSign',
  findUser: 'findUser',
  findUserId: 'findUserId',
  findPassword: 'findPassword',
  resetPassword: 'resetPassword',
  mobileAuthenticationMain: 'mobileAuthenticationMain',
  mobileAuthenticationId: 'mobileAuthenticationId',
  mobileAuthenticationPassword: 'mobileAuthenticationPassword',
  moreMobileAuthenticationMyInfo: 'moreMobileAuthenticationMyInfo',
  nearbyAcademy: 'nearbyAcademy',
  academyMatchSchedule: 'academyMatchSchedule',
  academyMatchDetail: 'academyMatchDetail',
  academyDetail: 'academyDetail',
  academyIntroduction: 'academyIntroduction',
  academyPlayer: 'academyPlayer',
  academyRecruitment: 'academyRecruitment',
  academyRecruitmentDetail: 'academyRecruitmentDetail',
  academySchedule: 'academySchedule',
  academyCommunity: 'academyCommunity',
  academyCommunityDetail: 'academyCommunityDetail',
  searchAcademy: 'searchAcademy',
  matchingSchedule: 'matchingSchedule',
  matchingDetail: 'matchingDetail',
  matchingHistory: 'matchingHistory',
  matchingReview: 'matchingReview',
  tournamentDetail: 'tournamentDetail',
  alarmPage: 'alarmPage',
  communityDetails: 'communityDetails',
  playgroundDetail: 'playgroundDetail',
  moreArticle: 'moreArticle',
  moreArticleDetail: 'moreArticleDetail',
};

// bottomPage : 하단 네비게이션 페이지
const bottomPage = {
  home: 'home',
  academyMember: 'academyMember',
  matchingSchedule: 'matchingSchedule',
  community: 'community',
  communityFavPlayer: 'communityFavPlayer',
  training: 'training',
};

// prefix 연결
export const NAV_PREFIX = {
  auth: 'auth',
  noAuth: 'noAuth',
  bottom: 'bottom',
};

Object.keys(authPage).forEach(key => {
  authPage[key] = `${NAV_PREFIX.auth}-${authPage[key]}`;
});
Object.keys(noAuthPage).forEach(key => {
  noAuthPage[key] = `${NAV_PREFIX.noAuth}-${noAuthPage[key]}`;
});
Object.keys(bottomPage).forEach(key => {
  bottomPage[key] = `${NAV_PREFIX.bottom}-${bottomPage[key]}`;
});

export const navName = {
  ...authPage,
  ...noAuthPage,
  ...bottomPage,
};
