export const ORDER_TYPE = {
  REG_DATE_ASC: 'REG_DATE_ASC',
  REG_DATE_DESC: 'REG_DATE_DESC',
  RATING_ASC: 'RATING_ASC',
  RATING_DESC: 'RATING_DESC',
  REVIEW_CNT_ASC: 'REVIEW_CNT_ASC',
  REVIEW_CNT_DESC: 'REVIEW_CNT_DESC',
};
